### ISSUE TITLE
This PyOpenSSL won't compile against newer OpenSSL versions

### ISSUE THREAD

**Issue by df-cryptostorm** [sumanj/frankencert#4]
On CentOS 6.5 using OpenSSL 1.0.2a, I received this error when trying to compile pyOpenSSL with:
`python setup.py install`

OpenSSL/crypto/crl.c:6: error: static declaration of 'X509_REVOKED_dup' follows non-static declaration
/usr/include/openssl/x509.h:751: note: previous declaration of 'X509_REVOKED_dup' was here

Looks like later OpenSSL versions use an "X509_REVOKED_dup" already. 
(See https://github.com/openssl/openssl/blob/master/include/openssl/x509.h)

The quick/lazy fix for me was to change all "X509_REVOKED_dup" to "X509_REVOKED_dupe" in `OpenSSL/crypto/crl.c`. I.e.,

`sed -e's/X509_REVOKED_dup/X509_REVOKED_dupe/g' -i OpenSSL/crypto/crl.c`
(while in pyOpenSSL-0.13)

**Comment by sumanj** [comment]
Thanks for reporting this! Will fix it over this weekend.

**Comment by jantman** [comment]
FYI upgrading to pyOpenSSL >= 0.14 should fix this, see https://github.com/pyca/pyopenssl/issues/276

**Comment by sumanj** [comment]
Closing the issue as upgrading to pyOpenSSL >= 0.14 seem to fix it as noted by jantman.
